=== 2lambda123/magento-ece-tools/etc/di.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Schema for DI configuration
 *
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="argumentType" abstract="true" mixed="true">
        <xs:attribute name="name" use="required"/>
    </xs:complexType>

    <xs:complexType name="itemType" abstract="true" mixed="true">
        <xs:attribute name="sortOrder" use="required"/>
    </xs:complexType>

    <xs:element name="config">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="preference" type="preferenceType" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="preferenceType">
        <xs:annotation>
            <xs:documentation>
                Preference help Object Manager to choose class for corresponding interface
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="for" type="phpClassName" use="required"/>
        <xs:attribute name="type" type="phpClassName" use="required" />
    </xs:complexType>

    <xs:complexType name="typeType">
        <xs:annotation>
            <xs:documentation>
                With 'type' tag you can point parameters and plugins for certain class
            </xs:documentation>
        </xs:annotation>
        <xs:choice maxOccurs="unbounded">
            <xs:element name="arguments" type="argumentsType" minOccurs="0" maxOccurs="1">
                <xs:key name="argumentName">
                    <xs:selector xpath="argument"></xs:selector>
                    <xs:field xpath="@name"></xs:field>
                </xs:key>
            </xs:element>
            <xs:element name="composite" type="compositesType" minOccurs="0" maxOccurs="1" />
        </xs:choice>
        <xs:attribute name="name" type="phpClassName" use="required" />
        <xs:attribute name="shared" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:simpleType name="phpClassName">
        <xs:annotation>
            <xs:documentation>
                A string that matches a Fully Qualified Class Name from PHP, especially not starting
                with a backslash as this is an invalid character to start a class name with but a
                somewhat common mistake so this simple type can be used to validate against it
                already
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(\\?[a-zA-Z_&#x7f;-&#xff;][a-zA-Z0-9_&#x7f;-&#xff;]*)(\\[a-zA-Z_&#x7f;-&#xff;][a-zA-Z0-9_&#x7f;-&#xff;]*)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="argumentsType">
        <xs:sequence>
            <xs:element name="argument" type="argumentType" minOccurs="1" maxOccurs="unbounded">
                <xs:key name="argumentItemName">
                    <xs:selector xpath="item"></xs:selector>
                    <xs:field xpath="@name"></xs:field>
                </xs:key>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="compositesType">
        <xs:sequence>
            <xs:element name="item" type="itemType" minOccurs="1" maxOccurs="unbounded">
                <xs:key name="itemItemName">
                    <xs:selector xpath="item"></xs:selector>
                    <xs:field xpath="@name"></xs:field>
                </xs:key>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="string">
        <xs:complexContent>
        <xs:extension base="argumentType">
            <xs:attribute name="translate" type="xs:boolean"/>
        </xs:extension>
    </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== 2lambda123/magento-ece-tools/etc/di.xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="di.xsd">
    <type name="Magento\MagentoCloud\Config\Schema" />
    <type name="Magento\MagentoCloud\Config\Environment" />
    <type name="Magento\MagentoCloud\Config\State" />
    <type name="Magento\MagentoCloud\App\Logger\Pool" />
    <type name="Magento\MagentoCloud\Package\Manager" />
    <type name="Magento\MagentoCloud\Package\MagentoVersion" />
    <type name="Magento\MagentoCloud\Util\UrlManager" />
    <type name="Magento\MagentoCloud\Filesystem\DirectoryCopier\CopyStrategy" />
    <type name="Magento\MagentoCloud\Filesystem\DirectoryCopier\CopySubFolderStrategy" />
    <type name="Magento\MagentoCloud\Filesystem\DirectoryCopier\SymlinkStrategy" />
    <type name="Magento\MagentoCloud\Filesystem\DirectoryCopier\StrategyFactory" />
    <type name="Magento\MagentoCloud\Config\Build\Reader" />
    <type name="Magento\MagentoCloud\Config\Environment\Reader" />
    <type name="Magento\MagentoCloud\Config\Stage\Build" />
    <type name="Magento\MagentoCloud\Config\Stage\Deploy" />
    <type name="Magento\MagentoCloud\Config\Stage\PostDeploy" />
    <type name="Magento\MagentoCloud\Config\RepositoryFactory" />
    <type name="Magento\MagentoCloud\Shell\UtilityManager"/>
    <type name="Magento\MagentoCloud\Config\Schema" />
    <type name="Magento\MagentoCloud\Command\CronKill">
        <arguments>
            <argument name="Magento\MagentoCloud\Process\ProcessInterface" xsi:type="string">Magento\MagentoCloud\Process\Deploy\CronProcessKill</argument>
        </arguments>
    </type>
    <type name="Magento\MagentoCloud\Command\DbDump">
        <composite>
            <item name="dbdump" sortOrder="10">Magento\MagentoCloud\Process\DbDump\DbDump</item>
        </composite>
    </type>
    <type name="Magento\MagentoCloud\Process\Deploy\DeployStaticContent">
        <composite>
            <item name="generate" sortOrder="10">Magento\MagentoCloud\Process\Deploy\DeployStaticContent\Generate</item>
        </composite>
    </type>
    <type name="Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Urls">
        <composite>
            <item name="database" sortOrder="10">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Urls\Database</item>
            <item name="environment" sortOrder="20">Magento\MagentoCloud\Process\Deploy\InstallUpdate\ConfigUpdate\Urls\Environment</item>
        </composite>
    </type>
    <type name="Magento\MagentoCloud\Process\Build\DeployStaticContent">
        <composite>
            <item name="generate" sortOrder="10">Magento\MagentoCloud\Process\Build\DeployStaticContent\Generate</item>
        </composite>
    </type>
    <type name="Magento\MagentoCloud\Process\Build\BackupData">
        <composite>
            <item name="static" sortOrder="10">Magento\MagentoCloud\Process\Build\BackupData\StaticContent</item>
            <item name="static" sortOrder="20">Magento\MagentoCloud\Process\Build\BackupData\WritableDirectories</item>
        </composite>
    </type>
    <type name="Magento\MagentoCloud\Process\Deploy\PreDeploy">
        <composite>
            <item name="cache" sortOrder="10">Magento\MagentoCloud\Process\Deploy\PreDeploy\ConfigUpdate\Cache</item>
            <item name="clean-static-content" sortOrder="20">Magento\MagentoCloud\Process\Deploy\PreDeploy\CleanStaticContent</item>
            <item name="clean-view-preprocessed" sortOrder="30">Magento\MagentoCloud\Process\Deploy\PreDeploy\CleanViewPreprocessed</item>
            <item name="clean-redis-cache" sortOrder="40">Magento\MagentoCloud\Process\Deploy\PreDeploy\CleanRedisCache</item>
            <item name="clean-file-cache" sortOrder="50">Magento\MagentoCloud\Process\Deploy\PreDeploy\CleanFileCache</item>
            <item name="restore-writable-dirs" sortOrder="60">Magento\MagentoCloud\Process\Deploy\PreDeploy\RestoreWritableDirectories</item>
            <item name="set-production-mode" sortOrder="70">Magento\MagentoCloud\Process\Deploy\PreDeploy\SetProductionMode</item>
        </composite>
    </type>
    <preference for="Magento\MagentoCloud\Config\ConfigInterface" type="Magento\MagentoCloud\Config\Shared" />
    <preference for="Magento\MagentoCloud\Shell\ShellInterface" type="Magento\MagentoCloud\Shell\Shell" />
    <preference for="Magento\MagentoCloud\DB\DumpInterface" type="Magento\MagentoCloud\DB\Dump" />
    <preference for="Psr\Log\LoggerInterface" type="Magento\MagentoCloud\App\Logger" />
    <preference for="Magento\MagentoCloud\DB\ConnectionInterface" type="Magento\MagentoCloud\DB\Connection" />
    <preference for="Magento\MagentoCloud\Config\Stage\BuildInterface" type="Magento\MagentoCloud\Config\Stage\Build" />
    <preference for="Magento\MagentoCloud\Config\Stage\DeployInterface" type="Magento\MagentoCloud\Config\Stage\Deploy"/>
    <preference for="Magento\MagentoCloud\Config\Stage\PostDeployInterface" type="Magento\MagentoCloud\Config\Stage\PostDeploy" />
    <preference for="Magento\MagentoCloud\View\RendererInterface" type="Magento\MagentoCloud\View\TwigRenderer" />
    <preference for="Magento\MagentoCloud\Config\Database\ConfigInterface" type="Magento\MagentoCloud\Config\Database\MergedConfig" />
</config>
